services:
  - type: web
    name: railsafe-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TRAIN_API_KEY
        value: rg_874fe1703f654373bd3fdef5840ad1ee
      - key: RAILSAFE_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.8
